// Hardcoded genre map — fallback for films where DB genres are empty.
// Keys are exact film titles from the `films` table.
export const FILM_GENRE_MAP: Record<string, string[]> = {
  // ── Studio catalog ─────────────────────────────────────────────────────
  // 2025
  "Marty Supreme":           ["Drama", "Comedy"],
  "Eternity":                ["Drama"],
  "The Smashing Machine":    ["Drama", "Action"],
  "Eddington":               ["Thriller", "Western", "Drama"],
  "Sorry, Baby":             ["Drama"],
  "Materialists":            ["Drama", "Romance", "Comedy"],
  "Bring Her Back":          ["Horror", "Drama", "Thriller"],
  "Friendship":              ["Comedy"],
  "The Legend of Ochi":      ["Adventure", "Family", "Fantasy"],
  "Warfare":                 ["War", "Drama", "Action"],
  "Death of a Unicorn":      ["Horror", "Comedy", "Fantasy"],
  "Opus":                    ["Horror", "Thriller"],
  // 2024
  "Babygirl":                ["Drama", "Thriller", "Romance"],
  "The Brutalist":           ["Drama"],
  "Queer":                   ["Drama", "Romance"],
  "Y2K":                     ["Comedy", "Horror"],
  "Heretic":                 ["Horror", "Thriller", "Mystery"],
  "We Live in Time":         ["Drama", "Romance"],
  "The Front Room":          ["Horror", "Thriller"],
  "Sing Sing":               ["Drama"],
  "Tuesday":                 ["Drama", "Fantasy"],
  "I Saw the TV Glow":       ["Horror", "Drama"],
  "Civil War":               ["Action", "Drama", "Thriller"],
  "Problemista":             ["Comedy", "Drama", "Fantasy"],
  "Love Lies Bleeding":      ["Thriller", "Crime", "Drama", "Romance"],
  "The Zone of Interest":    ["Drama"],
  // 2023
  "The Iron Claw":           ["Drama", "Action", "Biography"],
  "Dream Scenario":          ["Comedy", "Drama", "Fantasy"],
  "Priscilla":               ["Drama", "Romance", "Biography"],
  "Dicks: The Musical":      ["Comedy", "Musical"],
  "Past Lives":              ["Drama", "Romance"],
  "You Hurt My Feelings":    ["Comedy", "Drama"],
  "Beau Is Afraid":          ["Horror", "Drama", "Comedy"],
  // 2022
  "The Whale":               ["Drama"],
  "Bodies Bodies Bodies":    ["Comedy", "Horror", "Thriller"],
  "Marcel the Shell with Shoes On": ["Animation", "Comedy", "Drama"],
  "Men":                     ["Horror", "Drama", "Thriller"],
  "Everything Everywhere All at Once": ["Action", "Comedy", "Sci-Fi", "Drama"],
  // 2021
  "Red Rocket":              ["Comedy", "Drama"],
  "C'mon C'mon":             ["Drama"],
  "Lamb":                    ["Horror", "Drama", "Mystery"],
  "The Green Knight":        ["Fantasy", "Adventure", "Drama"],
  "Zola":                    ["Drama", "Thriller", "Comedy"],
  "Minari":                  ["Drama"],
  // 2019
  "Uncut Gems":              ["Thriller", "Crime", "Drama"],
  "The Lighthouse":          ["Horror", "Drama", "Mystery"],
  "The Farewell":            ["Comedy", "Drama"],
  "Gloria Bell":             ["Drama", "Romance"],
  // 2018
  "Mid90s":                  ["Drama"],
  "Eighth Grade":            ["Drama", "Comedy"],
  "First Reformed":          ["Drama", "Thriller"],
  // 2017
  "The Disaster Artist":     ["Comedy", "Drama", "Biography"],
  "Lady Bird":               ["Drama", "Comedy"],
  "A Ghost Story":           ["Drama", "Fantasy", "Horror"],
  "It Comes at Night":       ["Horror", "Thriller", "Drama"],
  "The Lovers":              ["Drama", "Romance", "Comedy"],
  // 2016
  "Moonlight":               ["Drama"],
  "Swiss Army Man":          ["Comedy", "Drama", "Fantasy"],
  "The Lobster":             ["Comedy", "Drama", "Sci-Fi", "Romance"],
  "The Witch":               ["Horror", "Drama"],
  "Room":                    ["Drama", "Thriller"],
  // 2015
  "Amy":                     ["Documentary"],
  "Ex Machina":              ["Sci-Fi", "Drama", "Thriller"],
  "While We're Young":       ["Comedy", "Drama"],
  // ── Arthouse horror ────────────────────────────────────────────────────
  "Hereditary": ["Horror", "Drama", "Thriller"],
  "Midsommar": ["Horror", "Drama", "Mystery"],
  "Talk to Me": ["Horror", "Thriller"],
  "The Black Phone": ["Horror", "Thriller"],
  "Smile": ["Horror", "Thriller"],
  "Smile 2": ["Horror", "Thriller"],
  "Get Out": ["Horror", "Thriller", "Drama"],
  "Us": ["Horror", "Thriller"],
  "Nope": ["Horror", "Sci-Fi", "Mystery"],
  "A Quiet Place": ["Horror", "Sci-Fi", "Thriller"],
  "A Quiet Place Part II": ["Horror", "Sci-Fi", "Thriller"],
  "A Quiet Place: Day One": ["Horror", "Sci-Fi", "Thriller"],
  "It": ["Horror"],
  "It Chapter Two": ["Horror"],
  "Halloween Kills": ["Horror"],
  "Halloween Ends": ["Horror"],
  "Scream": ["Horror", "Thriller"],
  "Scream VI": ["Horror", "Thriller"],
  "Scream VII": ["Horror", "Thriller"],
  "M3GAN": ["Horror", "Sci-Fi", "Thriller"],
  "Insidious: The Red Door": ["Horror", "Thriller"],
  "Evil Dead Rise": ["Horror"],
  "The Nun": ["Horror", "Thriller"],
  "The Nun II": ["Horror", "Thriller"],
  "Annabelle Comes Home": ["Horror", "Thriller"],
  "Malignant": ["Horror", "Thriller"],
  "Barbarian": ["Horror", "Thriller"],
  "Pearl": ["Horror"],
  "X": ["Horror", "Thriller"],
  "MaXXXine": ["Horror", "Thriller"],

  // ── Fall 2025 ─────────────────────────────────────────────────────────
  "Wicked: For Good": ["Musical", "Fantasy", "Romance"],
  "Zootopia 2": ["Animation", "Family", "Comedy", "Adventure"],
  "Avatar: Fire and Ash": ["Sci-Fi", "Action", "Adventure"],
  "The Conjuring: Last Rites": ["Horror", "Thriller"],
  "Weapons": ["Horror", "Thriller", "Crime"],
  "Demon Slayer: Kimetsu No Yaiba Infinity Castle": ["Animation", "Action", "Fantasy"],
  "Five Nights at Freddy's 2": ["Horror", "Thriller"],
  "The Fantastic Four: First Steps": ["Action", "Adventure", "Sci-Fi"],
  "Predator: Badlands": ["Sci-Fi", "Action", "Horror"],
  "Freakier Friday": ["Comedy", "Family"],
  "The Bad Guys 2": ["Animation", "Family", "Comedy", "Action"],
  "Tron: Ares": ["Sci-Fi", "Action", "Thriller"],
  "Black Phone 2": ["Horror", "Thriller"],
  "One Battle After Another": ["War", "Drama", "Action"],
  "Now You See Me: Now You Don't": ["Action", "Thriller", "Crime"],
  "The Naked Gun": ["Comedy", "Crime"],
  "David": ["Drama", "Action", "Historical"],
  "The Housemaid": ["Thriller", "Drama"],
  "Taylor Swift: The Official Release Party of a Showgirl": ["Music", "Concert"],
  "Superman": ["Action", "Adventure"],
  "Downton Abbey: The Grand Finale": ["Drama", "Romance"],
  "The Running Man": ["Sci-Fi", "Action", "Thriller"],
  "The SpongeBob Movie: Search for SquarePants": ["Animation", "Family", "Comedy"],
  "Regretting You": ["Romance", "Drama"],
  "Gabby's Dollhouse: The Movie": ["Family", "Animation"],
  "The Long Walk": ["Drama", "Thriller"],
  "Chainsaw Man - The Movie: Reze Arc": ["Animation", "Action", "Horror"],
  "Jurassic World: Rebirth": ["Action", "Adventure", "Sci-Fi"],
  "Him": ["Horror", "Thriller"],
  "KPop Demon Hunters": ["Action", "Comedy", "Music"],
  "Nobody 2": ["Action", "Thriller", "Crime"],
  "Anaconda": ["Horror", "Action", "Adventure"],
  "Roofman": ["Crime", "Drama", "Thriller"],
  "Hamilton": ["Musical", "Drama"],
  "F1: The Movie": ["Drama", "Action", "Sport"],
  "Jujutsu Kaisen: Execution": ["Animation", "Action", "Fantasy"],
  "Caught Stealing": ["Action", "Crime", "Thriller"],
  "Springsteen: Deliver Me from Nowhere": ["Documentary", "Music"],
  "The Strangers: Chapter 2": ["Horror", "Thriller"],
  "Together": ["Horror", "Sci-Fi"],
  "The Roses": ["Drama", "Romance"],
  "Good Fortune": ["Comedy", "Drama"],
  "Jaws": ["Horror", "Thriller", "Adventure"],
  "Nuremberg": ["Drama", "Historical", "War", "Crime"],
  "Dhurandhar": ["Action", "Thriller"],
  "Sarah's Oil": ["Drama", "Thriller"],
  "Hamnet": ["Drama", "Historical", "Romance"],
  "Bugonia": ["Comedy", "Sci-Fi"],
  "Rental Family": ["Comedy", "Drama"],
  "A Big Bold Beautiful Journey": ["Drama", "Romance"],
  "Good Boy": ["Horror", "Thriller"],
  "Kill Bill: The Whole Bloody Affair": ["Action", "Crime", "Thriller"],
  "Soul on Fire": ["Drama"],
  "Honey Don't!": ["Crime", "Thriller", "Comedy"],
  "Truth & Treason": ["Drama", "Thriller"],
  "Die My Love": ["Drama", "Thriller"],
  "Light of the World": ["Drama", "Documentary"],
  "Sketch": ["Drama", "Thriller"],
  "The Senior": ["Comedy", "Drama"],
  "I Know What You Did Last Summer": ["Horror", "Thriller"],
  "Avatar: The Way of Water": ["Sci-Fi", "Action", "Adventure"],
  "Sisu: Road to Revenge": ["Action", "Thriller", "War"],
  "Keeper": ["Drama", "Thriller"],
  "Shelby Oaks": ["Horror"],
  "Dead of Winter": ["Horror", "Thriller"],
  "Silent Night, Deadly Night": ["Horror"],
  "Bone Lake": ["Horror", "Thriller"],
  "Primitive War": ["Horror", "Sci-Fi", "Action"],
  "The Shining": ["Horror", "Thriller"],
  "Stitch Head": ["Horror", "Sci-Fi"],
  "Perfect Blue": ["Animation", "Thriller", "Horror"],
  "The Toxic Avenger": ["Action", "Comedy", "Horror"],
  "Shin Godzilla": ["Sci-Fi", "Action", "Horror"],
  "Sentimental Value": ["Drama", "Thriller"],
  "After the Hunt": ["Drama", "Thriller"],
  "Eden": ["Drama", "Thriller"],
  "The Secret Agent": ["Thriller", "Drama"],
  "Wake Up Dead Man": ["Mystery", "Thriller", "Crime"],
  "Relay": ["Action", "Thriller"],
  "War 2": ["Action", "Thriller"],
  "Coolie": ["Action", "Comedy"],
  "Back to the Future": ["Sci-Fi", "Comedy", "Adventure"],
  "The Sound of Music": ["Musical", "Drama", "Romance"],
  "Toy Story": ["Animation", "Family", "Comedy", "Adventure"],
  "Lilo & Stitch": ["Family", "Comedy", "Animation"],
  "Howl's Moving Castle": ["Animation", "Fantasy", "Romance"],
  "Spirited Away": ["Animation", "Fantasy"],
  "Ne Zha 2": ["Animation", "Fantasy", "Action"],
  "The Boy and the Heron": ["Animation", "Fantasy"],
  "How to Train Your Dragon": ["Animation", "Family", "Adventure"],
  "Smurfs": ["Animation", "Family", "Comedy"],
  "Spinal Tap II: The End Continues": ["Comedy", "Music"],
  "Casper": ["Family", "Comedy", "Fantasy"],
  "Spider-Man/Spider-Man 2/Spider-Man 3": ["Action", "Adventure"],
  "Elio": ["Animation", "Sci-Fi", "Family"],
  "How the Grinch Stole Christmas": ["Comedy", "Family", "Fantasy"],
  "Merrily We Roll Along": ["Musical", "Drama"],
  "Blue Moon": ["Musical", "Drama"],
  "Kiss of the Spider Woman": ["Drama", "Romance"],
  "Eleanor the Great": ["Comedy", "Drama"],
  "Ella McCay": ["Drama"],
  "No Other Choice": ["Drama"],
  "My Mother's Wedding": ["Comedy", "Romance"],
  "The Threesome": ["Comedy", "Romance"],
  "Splitsville": ["Comedy", "Romance"],
  "Christy": ["Drama", "Romance"],
  "The Christmas Ring": ["Romance", "Drama"],
  "Fackham Hall": ["Comedy", "Drama"],
  "In Whose Name?": ["Documentary", "Drama"],
  "It's Never Over, Jeff Buckley": ["Documentary", "Music"],
  "Sight & Sound Presents: NOAH Live": ["Documentary", "Music"],
  "CatVideoFest 2025": ["Documentary", "Comedy"],
  "UFC 319: du Plessis vs. Chimaev in COSM Shared Reality": ["Documentary", "Sport"],
  "Pets on a Train": ["Family", "Comedy"],

  // ── Prestige / drama ──────────────────────────────────────────────────
  "Oppenheimer": ["Drama", "Historical", "Thriller"],
  "Barbie": ["Comedy", "Fantasy", "Adventure"],
  "Poor Things": ["Drama", "Comedy", "Fantasy"],
  "Aftersun": ["Drama"],
  "Tár": ["Drama", "Music"],
  "All Quiet on the Western Front": ["War", "Drama"],
  "Parasite": ["Thriller", "Drama", "Comedy"],
  "The Banshees of Inisherin": ["Drama", "Comedy"],
  "Women Talking": ["Drama"],
  "Belfast": ["Drama"],
  "CODA": ["Drama"],
  "Spencer": ["Drama", "Historical"],
  "Licorice Pizza": ["Drama", "Romance", "Comedy"],
  "Drive My Car": ["Drama"],
  "Nightmare Alley": ["Thriller", "Drama"],

  // ── Action / blockbuster ──────────────────────────────────────────────
  "Top Gun: Maverick": ["Action", "Drama", "Thriller"],
  "Top Gun": ["Action", "Drama"],
  "Mission: Impossible - The Final Reckoning": ["Action", "Thriller"],
  "Mission: Impossible – Dead Reckoning Part One": ["Action", "Thriller"],
  "Mission: Impossible - Fallout": ["Action", "Thriller"],
  "Mission: Impossible - Ghost Protocol": ["Action", "Thriller"],
  "John Wick: Chapter 4": ["Action", "Thriller", "Crime"],
  "John Wick: Chapter 3 - Parabellum": ["Action", "Thriller", "Crime"],
  "The Batman": ["Action", "Crime", "Thriller"],
  "Thor: Love and Thunder": ["Action", "Adventure", "Comedy"],
  "Doctor Strange in the Multiverse of Madness": ["Action", "Adventure", "Sci-Fi"],
  "Spider-Man: No Way Home": ["Action", "Adventure"],
  "Avengers: Endgame": ["Action", "Adventure", "Sci-Fi"],
  "Avengers: Infinity War": ["Action", "Adventure", "Sci-Fi"],
  "Black Panther": ["Action", "Adventure"],
  "Black Panther: Wakanda Forever": ["Action", "Adventure"],
  "Captain Marvel": ["Action", "Adventure", "Sci-Fi"],
  "Captain America: Civil War": ["Action", "Adventure"],
  "Black Widow": ["Action", "Thriller"],
  "Shang-Chi and the Legend of the Ten Rings": ["Action", "Adventure"],
  "Eternals": ["Action", "Adventure", "Drama"],
  "Thor: Ragnarok": ["Action", "Adventure", "Comedy"],
  "Guardians of the Galaxy: Vol. 2": ["Action", "Adventure", "Comedy"],
  "Guardians of the Galaxy Vol. 3": ["Action", "Adventure", "Comedy"],
  "Ant-Man and the Wasp: Quantumania": ["Action", "Adventure"],
  "The Marvels": ["Action", "Adventure"],
  "Deadpool & Wolverine": ["Action", "Comedy"],
  "Deadpool": ["Action", "Comedy"],
  "Deadpool 2": ["Action", "Comedy"],
  "Fast X": ["Action", "Thriller", "Crime"],
  "F9": ["Action", "Thriller", "Crime"],
  "Fate of the Furious": ["Action", "Thriller", "Crime"],
  "Furious 7": ["Action", "Thriller", "Crime"],
  "Jurassic World": ["Action", "Adventure", "Sci-Fi"],
  "Jurassic World: Fallen Kingdom": ["Action", "Adventure", "Sci-Fi"],
  "Jurassic World Dominion": ["Action", "Adventure", "Sci-Fi"],
  "Transformers: Rise of the Beasts": ["Action", "Adventure", "Sci-Fi"],

  // ── Animated / family ─────────────────────────────────────────────────
  "Inside Out 2": ["Animation", "Family", "Comedy"],
  "Inside Out": ["Animation", "Family", "Comedy"],
  "The Super Mario Bros. Movie": ["Animation", "Family", "Comedy", "Adventure"],
  "Incredibles 2": ["Animation", "Family", "Action"],
  "Finding Dory": ["Animation", "Family"],
  "Frozen II": ["Animation", "Family", "Musical"],
  "Encanto": ["Animation", "Family", "Musical"],
  "Moana": ["Animation", "Family", "Musical"],
  "Moana 2": ["Animation", "Family", "Musical"],
  "The Lion King": ["Animation", "Family", "Musical"],
  "Beauty and the Beast": ["Animation", "Family", "Musical", "Romance"],
  "Minions: The Rise of Gru": ["Animation", "Family", "Comedy"],
  "Despicable Me 4": ["Animation", "Family", "Comedy"],
  "Puss in Boots: The Last Wish": ["Animation", "Family", "Comedy"],
  "Sonic the Hedgehog 2": ["Animation", "Family", "Action", "Comedy"],
  "Sonic the Hedgehog 3": ["Animation", "Family", "Action", "Comedy"],
  "A Minecraft Movie": ["Animation", "Family", "Adventure"],
  "Toy Story 4": ["Animation", "Family"],
  "Rogue One: A Star Wars Story": ["Action", "Adventure", "Sci-Fi"],
  "Star Wars: Episode VII - The Force Awakens": ["Action", "Adventure", "Sci-Fi"],
  "Star Wars: Episode VIII - The Last Jedi": ["Action", "Adventure", "Sci-Fi"],
  "Star Wars: Episode IX - The Rise of Skywalker": ["Action", "Adventure", "Sci-Fi"],

  // ── Sci-Fi / thriller ─────────────────────────────────────────────────
  "Dune: Part Two": ["Sci-Fi", "Adventure", "Drama"],
  "Dune: Part One": ["Sci-Fi", "Adventure", "Drama"],
  "Interstellar": ["Sci-Fi", "Drama", "Adventure"],
  "Tenet": ["Sci-Fi", "Action", "Thriller"],
  "Inception": ["Sci-Fi", "Action", "Thriller"],
  "The Matrix Resurrections": ["Sci-Fi", "Action"],
  "Avatar": ["Sci-Fi", "Action", "Adventure"],

  // ── Drama / thriller ──────────────────────────────────────────────────
  "Elvis": ["Drama", "Musical", "Biographical"],
  "Bohemian Rhapsody": ["Drama", "Musical", "Biographical"],
  "Rocketman": ["Drama", "Musical", "Biographical"],
  "Judy": ["Drama", "Biographical"],
  "The Crown": ["Drama", "Historical"],
  "1917": ["War", "Drama"],
  "Dunkirk": ["War", "Drama", "Action"],
  "Killers of the Flower Moon": ["Drama", "Historical", "Crime", "Western"],
  "Napoleon": ["Drama", "Historical", "War"],
  "Ferrari": ["Drama", "Sport", "Biographical"],
  "May December": ["Drama", "Comedy"],
  "Saltburn": ["Drama", "Thriller"],
  "Society of the Snow": ["Drama", "Thriller", "Historical"],
  "American Fiction": ["Drama", "Comedy"],
  "Rustin": ["Drama", "Historical"],
  "Maestro": ["Drama", "Biographical", "Romance"],
  "Nyad": ["Drama", "Sport", "Biographical"],
  "Cabrini": ["Drama", "Historical"],
  "Bob Marley: One Love": ["Drama", "Biographical", "Musical"],
  "Luther: The Fallen Sun": ["Thriller", "Crime", "Drama"],
  "The Beekeeper": ["Action", "Thriller"],
  "Lift": ["Action", "Comedy", "Crime"],
  "The Gentlemen": ["Comedy", "Crime", "Action"],
  "Guy Ritchie's The Covenant": ["Action", "War", "Thriller"],
  "Rebel Ridge": ["Action", "Thriller", "Crime"],
  "The Killer": ["Thriller", "Drama", "Crime"],
  "All of Us Strangers": ["Drama", "Romance"],
  "Monster": ["Drama", "Thriller"],
  "Perfect Days": ["Drama"],
  "Fallen Leaves": ["Drama", "Romance"],
  "Anatomie d'une chute": ["Drama", "Thriller", "Crime"],
  "The Teachers' Lounge": ["Drama", "Thriller"],

  // ── Comedy / romance ──────────────────────────────────────────────────
  "Ticket to Paradise": ["Comedy", "Romance"],
  "Bros": ["Comedy", "Romance"],
  "Fire Island": ["Comedy", "Romance"],
  "Marry Me": ["Comedy", "Romance"],
  "Shotgun Wedding": ["Action", "Comedy", "Romance"],
  "You People": ["Comedy", "Drama", "Romance"],
  "The Out-Laws": ["Comedy", "Action"],
  "No Hard Feelings": ["Comedy", "Romance"],
  "Red, White & Royal Blue": ["Comedy", "Romance"],
  "About My Father": ["Comedy"],
  "Joy Ride": ["Comedy", "Adventure"],
  "Theater Camp": ["Comedy"],
  "Strays": ["Comedy"],
  "Blue Beetle": ["Action", "Adventure", "Comedy"],

  // ── Wicked franchise ──────────────────────────────────────────────────
  "Wicked": ["Musical", "Fantasy", "Romance"],
};

export function getGenresForFilm(title: string, dbGenres: string[]): string[] {
  if (dbGenres.length > 0) return dbGenres;
  return FILM_GENRE_MAP[title] ?? [];
}
